server:
  port: 8088

spring:
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://106.54.138.86:3306/springboot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      max-idle: 10        # 连接池最大的空闲连接数量
      max-wait: 10000     # 连接池等待连接返回的最大等待时间
      min-idle: 5         # 必须保持连接的最小值
      initial-size: 5     # 启动连接池时，初始建立的连接数量
      validation-query: SELECT 1    # 获取连接时连接校验的sql查询语句
      test-on-borrow: false  # 从连接池借用连接时，是否测试该连接
      test-while-idle: true  # 当连接空闲时，是否执行连接测试
      time-between-eviction-runs-millis: 20000  # 空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔
    slaver:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://106.54.138.86:3306/springboot_slave?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 20000
  activemq:
    broker-url: tcp://127.0.0.1:61616
    in-memory: true
    password: admin
    pool:
      enabled: false
      expiry-timeout: 10000
      idle-timeout: 30000
      max-connections: 50
    user: admin
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  jms:
    pub-sub-domain: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        max-idle: 200
        max-wait: ''
        min-idle: 0
    password: ''
    port: 6379
    timeout: 1000
  resources:
    static-locations: classpath:/static
  servlet:
    multipart:
      max-file-size: 5MB

logging:
  level:
    com.example.xiongfk.mapper: debug
  config: config: classpath:logback.xml
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
