package com.xiongfk.springBooting.model;

import java.util.Date;

public class EbizProductRisk {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.sid
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private Integer sid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.risk_code
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String riskCode;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.version
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String version;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.out_risk_code
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String outRiskCode;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.risk_name
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String riskName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.short_name
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String shortName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.mng_com
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String mngCom;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.risk_type
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String riskType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.risk_sub_type
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String riskSubType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.risk_prop
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String riskProp;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.risk_period
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String riskPeriod;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.risk_state
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String riskState;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.orig_risk_code
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String origRiskCode;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.main_flag
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String mainFlag;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.remark
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String remark;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.create_date
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private Date createDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.creator_id
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private Integer creatorId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.modify_date
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private Date modifyDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.modifier_id
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private Integer modifierId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.stand_by_flag1
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String standByFlag1;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.stand_by_flag2
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String standByFlag2;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.stand_by_flag3
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String standByFlag3;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.stand_by_flag4
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String standByFlag4;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ebiz_product_risk.stand_by_flag5
     *
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    private String standByFlag5;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.sid
     *
     * @return the value of ebiz_product_risk.sid
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.sid
     *
     * @param sid the value for ebiz_product_risk.sid
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.risk_code
     *
     * @return the value of ebiz_product_risk.risk_code
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getRiskCode() {
        return riskCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.risk_code
     *
     * @param riskCode the value for ebiz_product_risk.risk_code
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setRiskCode(String riskCode) {
        this.riskCode = riskCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.version
     *
     * @return the value of ebiz_product_risk.version
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.version
     *
     * @param version the value for ebiz_product_risk.version
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.out_risk_code
     *
     * @return the value of ebiz_product_risk.out_risk_code
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getOutRiskCode() {
        return outRiskCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.out_risk_code
     *
     * @param outRiskCode the value for ebiz_product_risk.out_risk_code
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setOutRiskCode(String outRiskCode) {
        this.outRiskCode = outRiskCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.risk_name
     *
     * @return the value of ebiz_product_risk.risk_name
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getRiskName() {
        return riskName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.risk_name
     *
     * @param riskName the value for ebiz_product_risk.risk_name
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setRiskName(String riskName) {
        this.riskName = riskName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.short_name
     *
     * @return the value of ebiz_product_risk.short_name
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.short_name
     *
     * @param shortName the value for ebiz_product_risk.short_name
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.mng_com
     *
     * @return the value of ebiz_product_risk.mng_com
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getMngCom() {
        return mngCom;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.mng_com
     *
     * @param mngCom the value for ebiz_product_risk.mng_com
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setMngCom(String mngCom) {
        this.mngCom = mngCom;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.risk_type
     *
     * @return the value of ebiz_product_risk.risk_type
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getRiskType() {
        return riskType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.risk_type
     *
     * @param riskType the value for ebiz_product_risk.risk_type
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setRiskType(String riskType) {
        this.riskType = riskType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.risk_sub_type
     *
     * @return the value of ebiz_product_risk.risk_sub_type
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getRiskSubType() {
        return riskSubType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.risk_sub_type
     *
     * @param riskSubType the value for ebiz_product_risk.risk_sub_type
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setRiskSubType(String riskSubType) {
        this.riskSubType = riskSubType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.risk_prop
     *
     * @return the value of ebiz_product_risk.risk_prop
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getRiskProp() {
        return riskProp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.risk_prop
     *
     * @param riskProp the value for ebiz_product_risk.risk_prop
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setRiskProp(String riskProp) {
        this.riskProp = riskProp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.risk_period
     *
     * @return the value of ebiz_product_risk.risk_period
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getRiskPeriod() {
        return riskPeriod;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.risk_period
     *
     * @param riskPeriod the value for ebiz_product_risk.risk_period
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setRiskPeriod(String riskPeriod) {
        this.riskPeriod = riskPeriod;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.risk_state
     *
     * @return the value of ebiz_product_risk.risk_state
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getRiskState() {
        return riskState;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.risk_state
     *
     * @param riskState the value for ebiz_product_risk.risk_state
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setRiskState(String riskState) {
        this.riskState = riskState;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.orig_risk_code
     *
     * @return the value of ebiz_product_risk.orig_risk_code
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getOrigRiskCode() {
        return origRiskCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.orig_risk_code
     *
     * @param origRiskCode the value for ebiz_product_risk.orig_risk_code
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setOrigRiskCode(String origRiskCode) {
        this.origRiskCode = origRiskCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.main_flag
     *
     * @return the value of ebiz_product_risk.main_flag
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getMainFlag() {
        return mainFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.main_flag
     *
     * @param mainFlag the value for ebiz_product_risk.main_flag
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setMainFlag(String mainFlag) {
        this.mainFlag = mainFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.remark
     *
     * @return the value of ebiz_product_risk.remark
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.remark
     *
     * @param remark the value for ebiz_product_risk.remark
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.create_date
     *
     * @return the value of ebiz_product_risk.create_date
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.create_date
     *
     * @param createDate the value for ebiz_product_risk.create_date
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.creator_id
     *
     * @return the value of ebiz_product_risk.creator_id
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.creator_id
     *
     * @param creatorId the value for ebiz_product_risk.creator_id
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.modify_date
     *
     * @return the value of ebiz_product_risk.modify_date
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.modify_date
     *
     * @param modifyDate the value for ebiz_product_risk.modify_date
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.modifier_id
     *
     * @return the value of ebiz_product_risk.modifier_id
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public Integer getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.modifier_id
     *
     * @param modifierId the value for ebiz_product_risk.modifier_id
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setModifierId(Integer modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.stand_by_flag1
     *
     * @return the value of ebiz_product_risk.stand_by_flag1
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getStandByFlag1() {
        return standByFlag1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.stand_by_flag1
     *
     * @param standByFlag1 the value for ebiz_product_risk.stand_by_flag1
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setStandByFlag1(String standByFlag1) {
        this.standByFlag1 = standByFlag1;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.stand_by_flag2
     *
     * @return the value of ebiz_product_risk.stand_by_flag2
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getStandByFlag2() {
        return standByFlag2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.stand_by_flag2
     *
     * @param standByFlag2 the value for ebiz_product_risk.stand_by_flag2
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setStandByFlag2(String standByFlag2) {
        this.standByFlag2 = standByFlag2;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.stand_by_flag3
     *
     * @return the value of ebiz_product_risk.stand_by_flag3
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getStandByFlag3() {
        return standByFlag3;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.stand_by_flag3
     *
     * @param standByFlag3 the value for ebiz_product_risk.stand_by_flag3
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setStandByFlag3(String standByFlag3) {
        this.standByFlag3 = standByFlag3;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.stand_by_flag4
     *
     * @return the value of ebiz_product_risk.stand_by_flag4
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getStandByFlag4() {
        return standByFlag4;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.stand_by_flag4
     *
     * @param standByFlag4 the value for ebiz_product_risk.stand_by_flag4
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setStandByFlag4(String standByFlag4) {
        this.standByFlag4 = standByFlag4;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ebiz_product_risk.stand_by_flag5
     *
     * @return the value of ebiz_product_risk.stand_by_flag5
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public String getStandByFlag5() {
        return standByFlag5;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ebiz_product_risk.stand_by_flag5
     *
     * @param standByFlag5 the value for ebiz_product_risk.stand_by_flag5
     * @mbggenerated Thu Mar 02 17:22:04 CST 2017
     */
    public void setStandByFlag5(String standByFlag5) {
        this.standByFlag5 = standByFlag5;
    }
}