package com.xiongfk.springBooting.model;

import java.io.Serializable;

public class EbizCommonCode implements Serializable {
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebiz_common_code.sys_code
     *
     * @mbggenerated Mon May 16 21:30:35 CST 2016
     */
    private String sysCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebiz_common_code.code_type
     *
     * @mbggenerated Mon May 16 21:30:35 CST 2016
     */
    private String codeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebiz_common_code.code_content
     *
     * @mbggenerated Mon May 16 21:30:35 CST 2016
     */
    private String codeContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebiz_common_code.trans_info
     *
     * @mbggenerated Mon May 16 21:30:35 CST 2016
     */
    private String transInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebiz_common_code.description
     *
     * @mbggenerated Mon May 16 21:30:35 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebiz_common_code.sid
     *
     * @return the value of ebiz_common_code.sid
     * @mbggenerated Mon May 16 21:30:35 CST 2016
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebiz_common_code.sid
     *
     * @param sid the value for ebiz_common_code.sid
     * @mbggenerated Mon May 16 21:30:35 CST 2016
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebiz_common_code.sys_code
     *
     * @return the value of ebiz_common_code.sys_code
     * @mbggenerated Mon May 16 21:30:35 CST 2016
     */
    public String getSysCode() {
        return sysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebiz_common_code.sys_code
     *
     * @param sysCode the value for ebiz_common_code.sys_code
     * @mbggenerated Mon May 16 21:30:35 CST 2016
     */
    public void setSysCode(String sysCode) {
        this.sysCode = sysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebiz_common_code.code_type
     *
     * @return the value of ebiz_common_code.code_type
     * @mbggenerated Mon May 16 21:30:35 CST 2016
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebiz_common_code.code_type
     *
     * @param codeType the value for ebiz_common_code.code_type
     * @mbggenerated Mon May 16 21:30:35 CST 2016
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebiz_common_code.code_content
     *
     * @return the value of ebiz_common_code.code_content
     * @mbggenerated Mon May 16 21:30:35 CST 2016
     */
    public String getCodeContent() {
        return codeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebiz_common_code.code_content
     *
     * @param codeContent the value for ebiz_common_code.code_content
     * @mbggenerated Mon May 16 21:30:35 CST 2016
     */
    public void setCodeContent(String codeContent) {
        this.codeContent = codeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebiz_common_code.trans_info
     *
     * @return the value of ebiz_common_code.trans_info
     * @mbggenerated Mon May 16 21:30:35 CST 2016
     */
    public String getTransInfo() {
        return transInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebiz_common_code.trans_info
     *
     * @param transInfo the value for ebiz_common_code.trans_info
     * @mbggenerated Mon May 16 21:30:35 CST 2016
     */
    public void setTransInfo(String transInfo) {
        this.transInfo = transInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebiz_common_code.description
     *
     * @return the value of ebiz_common_code.description
     * @mbggenerated Mon May 16 21:30:35 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebiz_common_code.description
     *
     * @param description the value for ebiz_common_code.description
     * @mbggenerated Mon May 16 21:30:35 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }
}